name : Deploy frontend and backend
on:
  push:
    branches:
      - main
 
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: # This section defines the permissions for the workflow especially for OIDC token request in this case
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with GCP via Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
 
      - name:  setup google cloud sdk
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: configure artifact registry
        run: |
          gcloud auth configure-docker gcr.io

      - name: configure docker
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/uv-container/backend:latest -f backend/Dockerfile backend/
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/uv-container/backend:latest

      - name: Deploy backend to cloud run
        run: |
          gcloud run deploy uv-container \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/uv-container/backend:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --quiet
