name : Deploy frontend and backend
on:
  push:
    branches:
      - main
 
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: # This section defines the permissions for the workflow especially for OIDC token request in this case
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id : auth
        name: Authenticate with GCP via Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: projects/939819617751/locations/global/workloadIdentityPools/uv-github/providers/github
          service_account: my-uv-sa@webproject98.iam.gserviceaccount.com

      - name: Configure Docker for Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: configure docker
        run: |

          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/uv-container/backend:latest -f backend/Dockerfile backend/
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/uv-container/backend:latest

      - name: Deploy backend to cloud run
        run: |
          gcloud run deploy uv-container \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/uv-container/backend:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --project ${{ secrets.GCP_PROJECT_ID }} \
            --quiet
