name : Deploy frontend and backend
on:
  push:
    branches:
      - main
 
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: # This section defines the permissions for the workflow especially for OIDC token request in this case
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
         project_id: ${{ secrets.GCP_PROJECT_ID }}
         service_account_key: ${{ secrets.GCP_USER_KEY }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build and push Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/webproject98/uv-container/backend1:latest -f backend/Dockerfile backend/
          docker push us-central1-docker.pkg.dev/webproject98/uv-container/backend1:latest

      - name: Deploy backend to cloud run
        run: |
          gcloud run deploy uv-container \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/uv-container/backend:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --project ${{ secrets.GCP_PROJECT_ID }} \
            --quiet
