name : Deploy frontend and backend
on:
  push:
    branches:
      - main
 
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: # This section defines the permissions for the workflow especially for OIDC token request in this case
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ secrets.GCP_PROJECT_ID }}

     

      - name: Build 
        run: |
          docker build -t us-central1-docker.pkg.dev/webproject98/uv-container/backend:latest -f backend/Dockerfile backend/
         

      - name : docker configure
        run: |
          gcloud auth configure-docker 
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      - name : push docker image
        run: |
          docker push us-central1-docker.pkg.dev/webproject98/uv-container/backend:latest
      - name: Deploy backend to Cloud Run
        run: |
          gcloud run deploy uv-container \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/uv-container/backend:latest \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --quiet
