name : Deploy frontend and backend
on:
  push:
    branches:
      - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name:  setup google cloud sdk
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: configure artifact registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: configure docker
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/uv-container/backend:latest -f backend/Dockerfile backend/
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/uv-container/backend:latest

      - name: Deploy backend to cloud run
        run: |
          gcloud run deploy uv-container \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/uv-container/backend:latest \
            --service-account my_uv_sa@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --project ${{ secrets.GCP_PROJECT_ID }} \
            --quiet
