name : Deploy frontend and backend
on:
  push:
    branches:
      - main
 
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: # This section defines the permissions for the workflow especially for OIDC token request in this case
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: my-uv-sa@webproject98.iam.gserviceaccount.com
     

      - name: Build 
        run: |
          docker build -t us-central1-docker.pkg.dev/webproject98/uv-container/backend:latest -f backend/Dockerfile backend/
         

      - name : docker configure
        run: |
          gcloud auth configure-docker 
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      - name : push docker image
        run: |
          docker push us-central1-docker.pkg.dev/webproject98/uv-container/backend:latest
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: uv-backend
          image: us-central1-docker.pkg.dev/webproject98/uv-container/backend:latest
          region: us-central1
          allow_unauthenticated: true
          project_id: webproject98